spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

anthropic:
  api-key: ${ANTHROPIC_API_KEY}
  model: claude-sonnet-4-6
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate

# neo4j:
#   uri: ${NEO4J_URI}
#   username: ${NEO4J_USERNAME}
#   password: ${NEO4J_PASSWORD}